### ISSUE TITLE
Bring all operative settings into widget itself

### ISSUE THREAD

**Issue by notuxius** [plasma-light/plasma-widget-spectacle#11]
Move 'Include mouse pointer', 'Delay time' and 'Copy capture to clipboard' settings into widget - for quick setting/toggling them. Hide these additional features in drop menu for less cluttered UI or add 'Show all settings' checkbox in widget's right click menu - for showing/hiding extra features..

Plus in order to don't duplicate functionality - Spectacle - not widget's settings can be launched from right click widget menu.

**Comment by UriHerrera** [comment]
Moved to #10
