### ISSUE TITLE
Configuration Window

### ISSUE THREAD

**Issue by azubieta** [plasma-light/plasma-widget-spectacle#3]
Settings:
- Waith timer,
- Include pointer,

![ssss](https://cloud.githubusercontent.com/assets/1138094/14727801/a7996d60-07fc-11e6-96e7-ad9484570cf9.jpg)

**Comment by azubieta** [comment]
Any other ideas ?

**Comment by UriHerrera** [comment]
- Delay
- Include cursor
- Format
- Maybe, an option to select an application to open the screenshot after capturing

These two are in the image:
- Remember rectangular region
- Autosave

CC: @star-buck

**Comment by star-buck** [comment]
before doing too many options, lets test the prototype with minimal options. if too many options, people can use full spectacle imo.

**Comment by UriHerrera** [comment]
Well it's more of a "let's choose from the possible options" than to add all of those. I vote adding to the options already in the mockup a format selection dropdown. That gives the plasmoid enough options to be customizable and enough room that it doesn't overlap Spectacle itself.

**Comment by star-buck** [comment]
lets go ahead and test the widget out then.

**Comment by UriHerrera** [comment]
I've tested out the fresh code, screenshots work there's still some quirks that we can fix down the road but nothing major, it's working. Though I'm having some issues with Spectacle myself.

So I thought about the configuration window, could it be that when autosaving is off the screenshot is saved to the clipboard?. That'd be really useful for example for quickly editing the images in Gimp or Inkscape.

**Comment by azubieta** [comment]
Done functionalities:
- Include mouse pointer
- Delay

**Comment by azubieta** [comment]
The capture region functionality it's only implemented in the latest version of spectacle, you will need it in order to make it work.

@UriHerrera Please submit the issues that you found.

**Comment by azubieta** [comment]
Please submit the issues that you found.

**Comment by UriHerrera** [comment]
@azubieta The latest released version or the git builds?. Let me check what version I have installed in my VM.

# 

I have version 15.12.3 I guess that's why it wasn't working.

**Comment by azubieta** [comment]
@UriHerrera You must have the las git build of spectacle in order to make it work.

**Comment by azubieta** [comment]
Are we going to add the option, "copy to clipboard" ?

**Comment by UriHerrera** [comment]
I upgraded to Spectacle 16.04.0 today, everything works!.

# 

I think copy to clipboard is a handy option.

**Comment by azubieta** [comment]
Ok, working on it?
Should I erase the file if the functionality "copy to clipboard" is enabled ?

**Comment by UriHerrera** [comment]
If it is enabled yeah.

**Comment by azubieta** [comment]
Done 059152cf440a9a07f5b73c2524810893a02dd626

**Comment by UriHerrera** [comment]
Tested, it's working nicely.
