### ISSUE TITLE
make exits with an error

### ISSUE THREAD

**Issue by UriHerrera** [plasma-light/plasma-widget-spectacle#4]
I can't seem to compile it. Here's the output when I use make: https://gist.github.com/UriHerrera/bbab0f410e3e3f9b932cffee9b85014a

This is the error specifically:

`spectacledbusadaptor.cpp: In member function ‘void SpectacleDbusAdaptor::captureArea(int)’:`
`spectacledbusadaptor.cpp:27:25: error: no matching function for call to ‘OrgKdeSpectacleInterface::ActiveWindow()’
     iface->ActiveWindow();`

**Comment by UriHerrera** [comment]
I was able to compile it by adding `true, false` to line 27 in `spectacledbusadaptor.cpp` but that causes the plasmoid to treat _Rectangular_ the same as _Window_. 

Other than that screenshots are taken and saved in the default path.

**Comment by azubieta** [comment]
Fixed.
