### ISSUE TITLE
Icons in plasmoid buttons

### ISSUE THREAD

**Issue by UriHerrera** [plasma-light/plasma-widget-spectacle#8]
The icons in the buttons are pixelated, they're not scaled properly. I notice that this happens in other plasmoids like Notes, maybe adding the icons as elements for the Plasma theme work?.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/3Cnx563.png)

The icons should be at 22px looks like they're being used at 16px.

**Comment by UriHerrera** [comment]
Looks like I don't have icons at all now:

![](http://i.imgur.com/xgDjxMN.png)

# 

If I add the absolute path it works:

![](http://i.imgur.com/vGck9rq.png)

**Comment by azubieta** [comment]
@UriHerrera whould you please give a little more info, it's being display well here.
By the way it's very handy this plasmoid !!! 
![screenshot_20160425_201413](https://cloud.githubusercontent.com/assets/1138094/14802879/80f90840-0b22-11e6-9297-d14c4d3f0aed.png)

**Comment by UriHerrera** [comment]
Hmm then it's my system. Let me try in a clean machine.

# 

@azubieta Here's a video, I used a clean Manjaro install, compiled the code but the buttons aren't showing for me.

https://drive.google.com/file/d/0B7tTOld4xNXCcG5YMWZiTGtkdE0/view?usp=sharing

**Comment by azubieta** [comment]
Sorry, I also had some dirt on my system, the issue was caused by a wrong property set to the buttons . Now it's fixed, plase test it.
8925d9dedee66fb9d5ed0efd6c5bd1b8cdd43596

**Comment by UriHerrera** [comment]
Yeah it's looking good now.
